version: '2'
services:
  yqblog:
    build:
      context: .
      dockerfile: Dockerfile
    image: yqblog:latest
    ports:
      - "9999:80"
      - "443:443"
    volumes:
      - "./config.yaml:/app/config.yaml"
      - "cache:/app/.cache"
    restart: unless-stopped